version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ricardo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: inmobiliaria 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
